[workspace]
members = [
    "shared"
]
resolver = "3"

[workspace.package]
edition = "2024"
repository = "https://github.com/atgeo/implore"
license = "Apache-2.0"
keywords = ["catholic"]
rust-version = "1.97"

[workspace.dependencies]
anyhow = "1.0.104"
boltffi = "0.29.3"
crux_core = "0.20.0"
serde = "1.0.229"
