name: ImploreApp
packages:
  Shared:
    path: ./generated/Shared
  App:
    path: ./generated/App
options:
  bundleIdPrefix: com.atgeo.implore
  developmentLanguage: en
  knownRegions:
    - en
    - fr
    - es
    - Base
attributes:
  BuildIndependentTargetsInParallel: true

targets:
  ImploreApp-iOS:
    type: application
    platform: iOS
    deploymentTarget: 18.0
    sources:
      - path: ImploreApp
        excludes:
          - "Info-*.plist"
      - path: ../content/observances
        type: folder
        buildPhase: resources
        headerVisibility: project

    scheme:
      management:
        shared: true
    settings:
      MARKETING_VERSION: ${CARGO_PKG_VERSION}
      CURRENT_PROJECT_VERSION: 1
      PRODUCT_BUNDLE_IDENTIFIER: com.atgeo.implore
      TARGETED_DEVICE_FAMILY: "1"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: GN6M9254RZ
      CODE_SIGN_IDENTITY: Apple Development
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: Shared
      - package: App
    info:
      path: ImploreApp/Info-iOS.plist
      properties:
        CFBundleDisplayName: Implore
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        ITSAppUsesNonExemptEncryption: false
        NSHumanReadableCopyright: "Copyright © 2026 Georges Kmeid. All rights reserved."
        CFBundleLocalizations:
          - en
          - fr
          - es
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen:
          UIColorName: Paper
