name: ImploreApp
packages:
  Shared:
    path: ./generated/Shared
  App:
    path: ./generated/App
options:
  bundleIdPrefix: com.atgeo.implore
  developmentLanguage: en
attributes:
  BuildIndependentTargetsInParallel: true

targets:
  ImploreApp-iOS:
    type: application
    platform: iOS
    deploymentTarget: 18.0
    sources:
      - path: ImploreApp
        excludes:
          - "Info-*.plist"
    scheme:
      management:
        shared: true
    dependencies:
      - package: Shared
      - package: App
    info:
      path: ImploreApp/Info-iOS.plist
      properties:
        CFBundleDisplayName: Implore
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
